### ISSUE TITLE
RIs being used by other sub-accounts

### ISSUE THREAD

**Issue by jeremyalan** [sportngin/sport_ngin_aws_auditor#33]
![image](https://cloud.githubusercontent.com/assets/1322578/21649208/733aa75c-d266-11e6-8d50-ad5ab35aaee9.png)

In Beyond the Scores, we have an extra Reserved Instances that is being used by a different sub-account.  It shows up in the AWS Auditor output, it would be nice to tag it or similar, so it doesn't show up in the audit.

Steps to reproduce:
* Open Slack, and type the following command
```
/aws-auditor-staging bts
```

**Comment by emmasax1** [comment]
Yes this makes sense. I believe that you can tag the instance yourself through the UI if you navigate to the instance. Then, you can set the date to expire as the expiration date for the RI, and the reason being that it's being used in a different account.
