### ISSUE TITLE
Tagged instances should show instance size

### ISSUE THREAD

**Issue by tsndqst** [sportngin/sport_ngin_aws_auditor#41]
The output for TAGGED instances should include the instance type.

**Comment by emmasax1** [comment]
I will make a PR that can address this enhancement request.

**Comment by emmasax1** [comment]
I will make a PR to address this enhancement request.

**Comment by emmasax1** [comment]
This will be added in https://github.com/sportngin/sport_ngin_aws_auditor/pull/43.
